blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/vector-costa-rica/REPO_NAME/issues/new?template=bug_report.yml
    about: Use this template to report bugs.
  - name: Feature Request
    url: https://github.com/vector-costa-rica/REPO_NAME/issues/new?template=feature_request.yml
    about: Use this template to suggest a new feature.
  - name: Documentation Request
    url: https://github.com/vector-costa-rica/REPO_NAME/issues/new?template=documentation_request.yml
    about: Use this template to request changes or additions to documentation.
  - name: General Task
    url: https://github.com/vector-costa-rica/REPO_NAME/issues/new?template=task.yml
    about: Use this template for tasks or enhancements.
  - name: Support Request
    url: https://github.com/vector-costa-rica/REPO_NAME/issues/new?template=support_request.yml
    about: Use this template to request help or troubleshooting.
