name: Sync Labels

on:
  push:
    paths:
      - ".github/labels.yml"

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Labeler
        run: npm install -g @srvaroa/labeler

      - name: Sync Labels
        run: labeler --org vector-costa-rica --file .github/labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
